sudo: required
services: -docker

before_install:
  - docker build -t redhook/test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true redhook/test npm run test

after_success:
  - docker build -t redhook/multi-client ./client
  - docker build -t redhook/multi-nginx ./nginx
  - docker build -t redhook/multi-server ./server
  - docker build -t redhook/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push redhook/multi-client
  - docker push redhook/multi-nginx
  - docker push redhook/multi-server
  - docker push redhook/multi-worker
